# Generated by Django 4.1.7 on 2023-04-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='code',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='group',
            new_name='donation',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='recomendation',
        ),
    ]
