# Generated by Django 4.1.7 on 2023-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_code_medicine_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='color',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
